### ISSUE TITLE
Coral no longer gives dead coral in furnace

### ISSUE THREAD

**Issue by aurel85** [ryandw11/CoralStay#2]
Hi,

Since 1.18.1 (I use Paper) the coral no longer cooks in the oven to give dead coral although I have activated this option in the config.

Wouldn't there be a problem with 1.18 at this level?
I don't have any errors in the logs, it just doesn't work at all.

Thanks in advance.

**Comment by ryandw11** [comment]
I'll look into this issue.

**Comment by ryandw11** [comment]
I tested it on Spigot 1.18 and everything seems to work properly. Coral still cooks in the furnace for me.

**Comment by aurel85** [comment]
I immediately suspected EnchantableBlocks because there had been a conflict in the past ( #1 ) and it is still with it. When I remove EnchantableBlocks, everything works normally. for CoralStay.

**Comment by ryandw11** [comment]
I thought that issue was resolved. Did it break in a recent update?

**Comment by aurel85** [comment]
I'm not sure if this is the same problem because indeed since then I haven't had any new problems with this bug.
The bug here looks new but is still related to this plugin.

**Comment by ryandw11** [comment]
The issue should be fixed now.

**Comment by aurel85** [comment]
Unfortunately it doesn't change anything for me :/

**Comment by aurel85** [comment]
Everything is ok, thank you for the rapidity.

**Comment by aurel85** [comment]
Hi,

The same problem is present with 1.18.2.

Thank you in advance.

**Comment by aurel85** [comment]
Hi,

The problem came back in 1.19.4.

Thank you in advance.

**Comment by ryandw11** [comment]
Do you have any additional details?

It works fine on 1.19.4 for me.

**Comment by aurel85** [comment]
Hi,

After many tests I finally found (almost) the source. Indeed, on a empty server and even with all my other plugins it works... On the other hand as soon as I do a /minecraft reload it prevents this feature from being effective. Is it related to my datapacks or just the /minecraft:reload command ? I use /minecraft:reload regularly for my datapacks.

My datapacks : 
![Capture](https://user-images.githubusercontent.com/24486147/231852155-191adf88-7e2b-42f0-8d62-b4de27ca4448.PNG)
